import type { Language } from "../i18n/translations"

export interface ProjectImage {
  url: string
  alt: {
    [key in Language]: string
  }
}

export interface Project {
  id: string
  title: {
    [key in Language]: string
  }
  shortDescription: {
    [key in Language]: string
  }
  description: {
    [key in Language]: string
  }
  tags: string[]
  mainImage?: ProjectImage,
  images?: ProjectImage[]
  repo?: string
  demo?: string
  featured: boolean
  private?: boolean
}

export const projects: Project[] = [
  {
    id: "ocpp-dlm",
    title: {
      es: "DLM multi-marca OCPP para cargadores de vehículos eléctricos",
      en: "OCPP Multi-brand DLM for EV chargers",
      ca: "DLM multi-marca OCPP per a carregadors de vehicles elèctrics",
    },
    shortDescription: {
      es: "Sistema de balanceo dinámico de carga para cargadores de vehículos eléctricos a través de OCPP, con su sistema de gestión como trabajo de fin de grado para el grado en ingeniería informática.",
      en: "Dynamic load balancing system for EV chargers built with OCPP, with its management system as a final degree project for computer engineering.",
      ca: "Sistema de balanceig dinàmic de càrrega per a carregadors de vehicles elèctrics a través d'OCPP, amb el seu sistema de gestió com a treball de fi de grau per al grau en enginyeria informàtica.",
    },
    description: {
      es: "Sistema desarrollado como parte del trabajo de fin de grado y como producto de uso privado para la empresa gestionada por mi familia, motivo por el cual no puedo proporcionar más que la siguiente información.\n\nEl sistema está dividido en tres partes principales:\n\n- Software DLM: Sistema de balanceo dinámico de carga para cargadores de vehículos eléctricos a través de OCPP 1.6, que permite una ejecución local 24/7, gestión remota, comunicación de los cargadores con plataformas de terceros y actualizaciones en tiempo real.\n\n- Backend: servidor central que recibe toda la información generada por las distintas estaciones de carga y permite la gestión de las mismas. A su vez, da soporte al backoffice frontal, permitiéndole gestionar el sistema y acceder a toda la información en tiempo real. Todo protegido a través del identificador corporativo.\n\n- Frontend: Backoffice web que permite la visualización del estado del sistema y la gestión de este. Disponible en modo claro y oscuro, así como la traducción al inglés, español y catalán. Los usuarios pueden identificarse a través de la cuenta corporativa de la empresa.\n\nHe desarrollado el sistema en solitario, desde el diseño de la arquitectura hasta la implementación de todas las funcionalidades. Cada parte del software intenta seguir los principios SOLID, así como el uso de patrones de diseño y buenas prácticas de desarrollo.\n\nQuiero agradecer a mi tutor del trabajo de fin de grado por su aportación y criterio tecnológico.",
      en: "System developed as part of my final degree project and as a product of private usage for the company managed by my family, which is why I cannot provide more information beyond the following.\n\nThe system is divided into three main parts:\n\n- DLM Software: A dynamic load balancing system for EV chargers through OCPP 1.6, enabling local 24/7 execution, remote management, communication between chargers and third-party platforms, and real-time updates.\n\n- Backend: A central server that receives all the information generated by the different charging stations and allows their management. It also exposes various API that the backoffice can use to manage the system and acces real time information. Everything is protected through the corporate identifier.\n\n- Frontend: A web backoffice that allows visualizing the system status and managing it. Available in light and dark mode, as well as translated into English, Spanish, and Catalan. Users can sign in through the company's corporate account.\n\nI have developed the system completely on my own, from the architecture design to the implementation of all features. Each part of the software tries to follow SOLID principles, as well as the use of design patterns and good development practices.\n\nI would like to thank my final degree project tutor for his contribution and technological insight.",
      ca: "Sistema desenvolupat com a part del treball de fi de grau i com a producte d'ús privat per a l'empresa gestionada per la meva família, motiu pel qual no puc proporcionar més informació que la següent.\n\nEl sistema està dividit en tres parts principals:\n\n- Programari DLM: Sistema de balanceig dinàmic de càrrega per a carregadors de vehicles elèctrics a través d'OCPP 1.6, que permet una execució local 24/7, gestió remota, comunicació dels carregadors amb plataformes de tercers i actualitzacions en temps real.\n\n- Backend: servidor central que rep tota la informació generada per les diferents estacions de càrrega i permet la gestió d'aquestes. Al mateix moment, dóna suport al backoffice frontal, permetent-li gestionar el sistema i accedir a tota la informació en temps real. Tot protegit a través de l'identificador corporatiu.\n\n- Frontend: Backoffice web que permet la visualització de l'estat del sistema i la gestió d'aquest. Disponible en mode clar i fosc, així com la traducció a l'anglès, espanyol i català. Els usuaris poden identificar-se a través del compte corporatiu de l'empresa.\n\nHe desenvolupat el sistema en solitari, des del disseny de l'arquitectura fins a la implementació de totes les funcionalitats. Cada part del programari intenta seguir els principis SOLID així com l'ús de patrons de disseny i bones pràctiques de desenvolupament.\n\nVull agrair al meu tutor del treball de fi de grau la seva aportació i criteri tecnològic.",
    },
    tags: ["Python", "OCPP", "Modbus", "MQTT", "NestJS", "Angular", "Socket.IO", "PostgreSQL", "InfluxDB", "Redis", "Telegraf", "Docker", "OAuth2.0" ],
    mainImage: {
      url: "projects/dlm/graph-connectors.png",
      alt: {
        es: "Gráfica consumo tiempo real para un cargador",
        en: "Real-time consumption graph for a charger",
        ca: "Gràfica de consum en temps real per a un carregador"
      }
    },
    images: [
      {
        url: "projects/dlm/home-page.png",
        alt: {
          es: "Página de inicio",
          en: "Home page",
          ca: "Pàgina d&apos;inici"
        }
      },
      {
        url: "projects/dlm/google-login.png",
        alt: {
          es: "Inicio de sesión con cuenta corporativa",
          en: "Login with corporate account",
          ca: "Inici de sessió amb compte corporatiu"
        }
      },
      {
        url: "projects/dlm/restricted-page.png",
        alt: {
          es: "Acceso restringido a usuarios no autorizados",
          en: "Restricted access for unauthorized users",
          ca: "Accés restringit per a usuaris no autoritzats"
        }
      },
      {
        url: "projects/dlm/station-list.png",
        alt: {
          es: "Gestion de estaciones",
          en: "Station view",
          ca: "Gestió d&apos;estacions"
        }
      },
      {
        url: "projects/dlm/station-detail.png",
        alt: {
          es: "Vista detallada de una estación",
          en: "Detailed view of a station",
          ca: "Vista detallada d&apos;una estació"
        }
      },
      {
        url: "projects/dlm/station-detail-chargers.png",
        alt: {
          es: "Vista detallada de los cargadores de una estación",
          en: "Detailed view of a station&apos;s chargers",
          ca: "Vista detallada dels carregadors d&apos;una estació"
        }
      },
      {
        url: "projects/dlm/charger-detail.png",
        alt: {
          es: "Vista detallada de un cargador",
          en: "Detailed view of a charger",
          ca: "Vista detallada d&apos;un carregador"
        }
      },
      {
        url: "projects/dlm/charger-logs.png",
        alt: {
          es: "Registros generados por un cargador",
          en: "Logs record for a charger",
          ca: "Registre generats per un carregador"
        }
      },
      {
        url: "projects/dlm/graph-connectors.png",
        alt: {
          es: "Gráfica consumo tiempo real para un cargador",
          en: "Real-time consumption graph for a charger",
          ca: "Gràfica de consum en temps real per a un carregador"
        }
      },
      {
        url: "projects/dlm/users-page.png",
        alt: {
          es: "Gestión y autorización de usuarios",
          en: "Users management and authorization",
          ca: "Gestió i autorització d&apos;usuaris"
        }
      },
      {
        url: "projects/dlm/user-preferences.png",
        alt: {
          es: "Preferencias de usuario",
          en: "User preferences",
          ca: "Preferències d&apos;usuari"
        }
      }
    ],
    featured: true,
  },
  {
    id: "ecofruit",
    title: {
      es: "EcoFruit - MarketPlace de productos agrícolas",
      en: "EcoFruit - Marketplace for farm products",
      ca: "EcoFruit - MarketPlace de productes agrícoles",
    },
    shortDescription: {
      es: "Aplicación nativa para Android que conecta agricultores locales con consumidores, facilitando la compra de productos frescos y sostenibles directamente desde el campo.",
      en: "Native Android application that connects local farmers with consumers, easing the purchase of fresh and sustainable products directly from the field.",
      ca: "Aplicació nativa per a Android que connecta agricultors locals amb consumidors, facilitant la compra de productes frescos i sostenibles directament des del camp.",
    },
    description: {
      es: "Proyecto realizado para la universidad como parte del trabajo de una asignatura. És una aplicación nativa para Android que conecta agricultores locales con consumidores, facilitando la compra de productos frescos y sostenibles directamente desde el campo. \n\nLa aplicación incluye algoritmo de recomendación basico de productos, seguir a agricultores y productos favoritos, añadir reviews tanto al producto como al productor así como un sistema de chat entre el cliente y el agricultor para resolver dudas sobre el producto o la entrega.\n\nEl backend está construido con Firebase y cloud Functions para las notificaciones push, mientras que el frontend está desarrollado con JetPack Compose para una experiencia de usuario fluida e intuitiva.\n\nTanto Firebase Cloud Functions como los scripts de sopoerte para generar datos mockeados en Firebase han sido implementados en Python. \n\nLa aplicación esta disponible en un tema oscuro y claro, así como la traducción al ingles, español y catalán.",
      en: "Project completed for university as part of the coursework. It is a native Android application that connects local farmers with consumers, easing the purchase of fresh and sustainable products directly from the field. \n\nThe application includes a basic product recommendation algorithm, following farmers and favorite products, adding reviews both to the product and the producer as well as a chat system between the customer and the farmer to resolve doubts about the product or delivery.\n\nThe backend is built with Firebase and cloud Functions for push notifications, while the frontend is developed with JetPack Compose for a smooth and intuitive user experience.\n\n Firebase Cloud Functions and some support scripts for generating mock data in Firebase have been implemented in Python. \n\nThe application is available with both dark and light themes and is translated into English, Spanish, and Catalan.",
      ca: "Projecte realitzat per a la universitat com a part del treball de una assignatura. És una aplicació nativa per a Android que connecta agricultors locals amb consumidors, facilitant la compra de productes frescos i sostenibles directament des del camp. \n\nL'aplicació inclou un algoritme de recomanació bàsic de productes, seguir agricultors i productes favorits, afegir ressenyes tant al producte com al productor així com un sistema de xat entre el client i l'agricultor per resoldre dubtes sobre el producte o l'entrega.\n\nEl backend està construït amb Firebase i cloud Functions per a les notificacions push, mentre que el frontend està desenvolupat amb JetPack Compose per a una experiència d'usuari fluida i intuïtiva.\n\n Tant Firebase Cloud Functions com els scripts de suport per generar dades mockeades en Firebase han estat implementats en Python. \n\nL'aplicació està disponible amb un tema fosc i clar, així com la traducció en anglès, castellà i català.",
    },
    tags: ["Kotlin", "Jetpack Compose", "Python", "Firebase", "Cloud Functions"],
    mainImage: {
      url: "projects/ecofruit/view-product.png", alt: {
        es: "Producto detallado",
        en: "Detailed Product view",
        ca: "Producte detallat"
      }
    }, 
    images: [
      {url: "projects/ecofruit/init.png", alt: {
        es: "Página incicial",
        en: "Launcher page",
        ca: "Pàgina inicial"
      }},
      {url: "projects/ecofruit/login.png", alt: {
        es: "Página de inicio de sesión",
        en: "Login page",
        ca: "Pàgina d&apos;inici de sessió"
      }},
      {url: "projects/ecofruit/home.png", alt: {
        es: "Menú principal",
        en: "Main menu",
        ca: "Menú principal"
      }},
      {url: "projects/ecofruit/search-products.png", alt: {
        es: "Búsqueda de productos",
        en: "Product search",
        ca: "Cerca de productes"
      }},
      {url: "projects/ecofruit/view-product.png", alt: {
        es: "Producto detallado",
        en: "Detailed Product view",
        ca: "Producte detallat"
      }},
      {url: "projects/ecofruit/add-reviews.png", alt: {
        es: "Agregar reseña a productos",
        en: "Add Review to products",
        ca: "Afegir ressenya a productes"
      }},
      {url: "projects/ecofruit/product-reviews.png", alt: {
        es: "Ver reseñas de los productos",
        en: "View Product Reviews",
        ca: "Veure ressenyes dels productes"
      }},
      {url: "projects/ecofruit/set-product-location.png", alt: {
        es: "Establecer ubicación del producto",
        en: "Set Product Location",
        ca: "Establir ubicació del producte"
      }},
      {url: "projects/ecofruit/edit-user-profile.png", alt: {
        es: "Editar perfil del usuario",
        en: "Edit User Profile",
        ca: "Editar perfil de l&apos;usuari"
      }},
      {url: "projects/ecofruit/view-profile-products.png", alt: {
        es: "Ver productos del usuario",
        en: "View User Products",
        ca: "Veure productes de l&apos;usuari"
      }},
      {url: "projects/ecofruit/view-profile-reviews.png", alt: {
        es: "Ver reseñas del usuario",
        en: "View User Reviews",
        ca: "Veure ressenyes de l&apos;usuari"
      }},
      {url: "projects/ecofruit/conversation.png", alt: {
        es: "Chat integrado",
        en: "Integrated chat",
        ca: "Xat integrat"
      }},
      {url: "projects/ecofruit/notification.png", alt: {
        es: "Notificaciones",
        en: "Notifications",
        ca: "Notificacions"
      }},
    ],
    repo: "https://github.com/Elcris1/PEX-EcoFruit",
    featured: true,
  },
  {
    id: "portfolio",
    title: {
      es: "Portfolio personal",
      en: "Personal portfolio",
      ca: "Portfolio personal",
    },
    shortDescription: {
      es: "Sitio web personal creado con Astro y Tailwind CSS para mostrar mis proyectos y experiencia profesional. Disponible en español, inglés y catalán, con modo oscuro y diseño responsive.",
      en: "Personal website built with Astro and Tailwind CSS to showcase my projects and professional experience. Available in Spanish, English, and Catalan, with dark mode and responsive design.",
      ca: "Lloc web personal creat amb Astro i Tailwind CSS per mostrar els meus projectes i experiència professional. Disponible en espanyol, anglès i català, amb mode fosc i disseny responsive.",
    },
    description: {
      es: "Portfolio personal creado con Astro y Tailwind CSS. El sitio incluye:\n\n- Diseño responsive adaptable a todos los dispositivos\n\n- Modo oscuro/claro con persistencia en localStorage\n\n- Soporte multi idioma (español, inglés, catalán)\n\n- Secciones de experiencia profesional, educación, proyectos y stack tecnológico\n\n- Despliegue automático con GitHub Actions\n\nEste proyecto es el que estás viendo ahora mismo.",
      en: "Personal portfolio built with Astro and Tailwind CSS. The site features:\n\n- Responsive design adaptable to all devices\n\n- Dark/light mode with localStorage persistence\n\n- Multi-language support (Spanish, English, Catalan)\n\n- Sections for professional experience, education, projects, and tech stack\n\n- Automatic deployment with GitHub Actions\n\nThis project is the one you are viewing right now.",
      ca: "Portfolio personal creat amb Astro i Tailwind CSS. El lloc inclou:\n\n- Disseny responsive adaptable a tots els dispositius\n\n- Mode fosc/clar amb persistència a localStorage\n\n- Suport multi idioma (espanyol, anglès, català)\n\n- Seccions d'experiència professional, educació, projectes i stack tecnològic\n\n- Desplegament automàtic amb GitHub Actions\n\nAquest projecte és el que estàs veient ara mateix.",
    },
    tags: ["Astro", "TypeScript", "Tailwind CSS", "i18n", "GitHub Actions"],
    repo: "https://github.com/Elcris1/portfolio",
    demo: "https://elcris1.github.io/portfolio/en",
    featured: false,
  },
//   {
//     title: {
//       es: "Sistema de Gestión Empresarial",
//       en: "Enterprise Management System",
//       ca: "Sistema de Gestió Empresarial",
//     },
//     shortDescription: {
//       es: "Sistema interno de gestión para una empresa de logística con módulos de inventario, pedidos y reporting.",
//       en: "Internal management system for a logistics company with inventory, orders and reporting modules.",
//       ca: "Sistema intern de gestió per a una empresa de logística amb mòduls d'inventari, comandes i reporting.",
//     },
//     description: {
//       es: "Desarrollé un sistema de gestión empresarial completo para una empresa de logística. El sistema incluye módulos de:\n\n- **Inventario**: Control de stock en tiempo real, alertas de stock mínimo, gestión de almacén\n\n- **Pedidos**: Creación y seguimiento de pedidos, estados de envío, integración con transportistas\n- **Reporting**: Dashboard con métricas clave, gráficos de ventas, informes exportables a PDF/Excel\n- **Usuarios**: Sistema de roles y permisos, historial de acciones\n\nEste fue un proyecto privado para un cliente, por lo que el código no está disponible públicamente.",
//       en: "I developed a complete enterprise management system for a logistics company. The system includes modules for:\n\n- **Inventory**: Real-time stock control, minimum stock alerts, warehouse management\n\n- **Orders**: Order creation and tracking, shipping statuses, carrier integration\n- **Reporting**: Dashboard with key metrics, sales charts, reports exportable to PDF/Excel\n- **Users**: Role and permission system, action history\n\nThis was a private project for a client, so the code is not publicly available.",
//       ca: "Vaig desenvolupar un sistema de gestió empresarial complet per a una empresa de logística. El sistema inclou mòduls de:\n\n- **Inventari**: Control d'estoc en temps real, alertes d'estoc mínim, gestió d'emmagatzematge\n- **Comandes**: Creació i seguiment de comandes, estats d'enviament, integració amb transportistes\n- **Reporting**: Dashboard amb mètriques clau, gràfics de vendes, informes exportables a PDF/Excel\n\n- **Usuaris**: Sistema de rols i permisos, historial d'accions\n\nAquest va ser un projecte privat per a un client, per la qual cosa el codi no està disponible públiquement.",
//     },
//     tags: ["Next.js", "TypeScript", "PostgreSQL", "Prisma", "Tailwind CSS"],
//     images: [],
//     featured: true,
//     private: true,
//   },
//   {
//     title: {
//       es: "Dashboard de APIs",
//       en: "API Dashboard",
//       ca: "Dashboard d'APIs",
//     },
//     shortDescription: {
//       es: "Dashboard para monitoreo y análisis de APIs con métricas en tiempo real.",
//       en: "Dashboard for API monitoring and analysis with real-time metrics.",
//       ca: "Dashboard per a monitorització i anàlisi d'APIs amb mètriques en temps real.",
//     },
//     description: {
//       es: "Dashboard de monitoreo para APIs internas. Permite visualizar métricas de uso, latencia, errores y uptime. Incluye alertas configurables por email y Slack, y generación de informes periódicos.\n\nLa interfaz utiliza gráficos interactivos con D3.js para visualización de datos.",
//       en: "Monitoring dashboard for internal APIs. Allows visualizing usage metrics, latency, errors and uptime. Includes configurable alerts via email and Slack, and periodic report generation.\n\nThe interface uses interactive charts with D3.js for data visualization.",
//       ca: "Dashboard de monitorització per a APIs internes. Permet visualitzar mètriques d'ús, latència, errors i uptime. Inclou alertes configurables per email i Slack, i generació d'informes periòdics.\n\nLa interfície utilitza gràfics interactius amb D3.js per a visualització de dades.",
//     },
//     tags: ["Next.js", "PostgreSQL", "D3.js", "TypeScript"],
//     mainImage: { url: "/projects/api/metrics.svg", alt: { es: "Métricas en tiempo real", en: "Real-time metrics", ca: "Mètriques en temps real" } },
//     images: [
//       { url: "/projects/api/metrics.svg", alt: { es: "Métricas en tiempo real", en: "Real-time metrics", ca: "Mètriques en temps real" } },
//     ],
//     repo: "https://github.com/",
//     featured: false,
//   },
//   {
//     title: {
//       es: "Proyecto Template",
//       en: "Template Project",
//       ca: "Projecte Template",
//     },
//     shortDescription: {
//       es: "Proyecto de prueba con galería de imágenes para demostrar la funcionalidad.",
//       en: "Test project with image gallery to demonstrate functionality.",
//       ca: "Projecte de prova amb galeria d'imatges per demostrar la funcionalitat.",
//     },
//     description: {
//       es: "Este es un proyecto de prueba creado para demostrar la funcionalidad de la galería de imágenes.\n\nLa galería permite:\n- Ver múltiples imágenes del proyecto\n- Navegar entre ellas fácilmente\n- Ver descripciones de cada imagen\n\nTodas las imágenes están organizadas en la carpeta `public/projects/`.",
//       en: "This is a test project created to demonstrate the image gallery functionality.\n\nThe gallery allows:\n- View multiple project images\n- Navigate between them easily\n- See descriptions for each image\n\nAll images are organized in the `public/projects/` folder.",
//       ca: "Aquest és un projecte de prova creat per demostrar la funcionalitat de la galeria d'imatges.\n\nLa galeria permet:\n- Veure múltiples imatges del projecte\n- Navegar entre elles fàcilment\n- Veure descripcions de cada imatge\n\nTotes les imatges estan organitzades a la carpeta `public/projects/`.",
//     },
//     tags: ["Astro", "TypeScript", "Template"],
//     mainImage: { url: "/projects/template/hero.svg", alt: { es: "Vista principal del proyecto", en: "Main project view", ca: "Vista principal del projecte" } },
//     images: [
//       { url: "/projects/template/hero.svg", alt: { es: "Vista principal del proyecto", en: "Main project view", ca: "Vista principal del projecte" } },
//       { url: "/projects/template/dashboard.svg", alt: { es: "Vista del dashboard", en: "Dashboard view", ca: "Vista del dashboard" } },
//       { url: "/projects/template/settings.svg", alt: { es: "Panel de configuración", en: "Settings panel", ca: "Panell de configuració" } },
//     ],
//     repo: "https://github.com/Elcris1/portfolio",
//     demo: "http://localhost:4321",
//     featured: true,
//   },
]